# Generated by Django 3.2.6 on 2021-09-07 18:51

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210907_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='author',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='description',
            field=wagtail.core.fields.RichTextField(null=True),
        ),
    ]
